name: CI + CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  JumpBoxDeploy:
    name: Deploy to Dev JumpBox Server
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: [self-hosted,ubuntu-latest]
    environment: 
      name: DevJumpServer
      url: 'http://www.google.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      
      - name: Build with Maven
        run: mvn clean install
      - name: Transfer build file to remote server2
        run: scp -i /home/vvdn/.ssh/viki_rsa target/*.war ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME_2 }}:/home/vvdn/
      - name: Set up SSH to remote 
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.HOSTNAME_2 }}
            port: ${{secrets.PORT}}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY_2 }}
            command_timeout: 30m
            script: | 
              mkdir example_folder
              echo "Folder 'example_folder' created successfully."  
              cd /home/vvdn/Documents/apache/apache-tomcat-9.0.73/bin
              ls
              ./shutdown.sh
              sleep 30
              cp /home/vvdn/*.war /home/vvdn/Documents/apache/apache-tomcat-9.0.73/webapps/
              ./startup.sh


  DeployDevServer:
    name: Deploy to Dev Server
    needs: [JumpBoxDeploy]
    runs-on: [self-hosted,ubuntu-latest]
    environment: 
      name: Development
      url: 'http://www.google.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          pwd

  DeployProdJumpServer:
    name: Deploy to Prod Jump Server 
    needs: [DeployDevServer]
    runs-on: [self-hosted,ubuntu-latest]
    environment: 
      name: JumpServer
      url: 'http://www.google.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deploy
        run: echo I am deploying! 
    
  DeployProd:
    name: Deploy to Production 
    needs: [DeployProdJumpServer]
    runs-on: [self-hosted,ubuntu-latest]
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deploy
        run: echo I am deploying! 
