name: CI + CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  JumpBoxDeploy:
    name: Deploy to Dev JumpBox Server
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: [self-hosted,ubuntu-latest]
    environment: 
      name: DevJumpServer
      url: 'http://www.google.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      
      - name: Build with Maven
        run: mvn clean install
      - name: Transfer build file to Dev-Jump server
        run: scp -i /home/vvdn/.ssh/viki_rsa target/*.war ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOSTNAME }}:/home/vvdn/
      

  DeployDevServer:
    name: Deploy to Dev Server
    needs: [JumpBoxDeploy]
    runs-on: [self-hosted,ubuntu-latest]
    environment: 
      name: Development
      url: 'http://www.google.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up SSH from Local to Jump Server 
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.JUMP_HOSTNAME }}
            port: ${{secrets.PORT}}
            username: ${{ secrets.JUMP_USERNAME }}
            key: ${{ secrets.LOCAL_SSH_KEY }}
            command_timeout: 30m
            script: | 
              echo "Logged into Jump Server"
              
      - name: Set up SSH from Jump to Dev Server 
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.DEV_HOSTNAME }}
            port: ${{secrets.PORT}}
            username: ${{ secrets.DEV_USERNAME }}
            key: ${{ secrets.JUMP_SSH_KEY }}
            command_timeout: 30m
            script: | 
              cd /home/vvdn/Documents/apache/apache-tomcat-9.0.73/bin
              echo "${{secrets.DEV_PASSWORD}}" | sudo -S su -c '
              ./shutdown.sh
              sleep 30
              cp /home/vvdn/*.war /home/vvdn/Documents/apache/apache-tomcat-9.0.73/webapps/
              ./startup.sh '


  DeployProdJumpServer:
    name: Deploy to Prod Jump Server 
    needs: [DeployDevServer]
    runs-on: [self-hosted,ubuntu-latest]
    environment: 
      name: JumpServer
      url: 'http://www.google.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deploy
        run: echo I am deploying! 
    
  DeployProd:
    name: Deploy to Production 
    needs: [DeployProdJumpServer]
    runs-on: [self-hosted,ubuntu-latest]
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deploy
        run: echo I am deploying! 
