name: CI + CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  JumpBoxDeploy:
    name: Jump Box Env
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: 
      name: DevJumpServer
      url: 'http://www.google.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      
      - name: Build with Maven
        run: mvn clean install
      
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: sample
          path: /home/runner/work/sampleAction/sampleAction/target/*.war

      - name: Copy Files
        run: | 
         pwd
         cp target/*.war /home/runner/work/sampleAction

  DeployDevServer:
    name: Deploy to Dev Server
    needs: [JumpBoxDeploy]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://www.google.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download WAR artifact
        uses: actions/download-artifact@v2
        with:
          name: sample
          path: /home/runner/work/sampleAction/target/
      - name: Deploy
        run: |
          pwd
          #ls 
          #cp target/*.war /home/runner/work/sampleAction/
          ls  /home/runner/work/sampleAction/target/

  DeployProdJumpServer:
    name: Deploy to Prod Jump Server 
    needs: [DeployDevServer]
    runs-on: ubuntu-latest
    environment: 
      name: JumpServer
      url: 'http://www.google.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deploy
        run: echo I am deploying! 
    
  DeployProd:
    name: Deploy to Production 
    needs: [DeployProdJumpServer]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deploy
        run: echo I am deploying! 
