name: Build Maven Project with Java 8
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '8'
    - name: Build with Maven
      run: mvn clean install     

    - name: Local Deployment
      run: |
        cp target/*.war /home/vvdn/Documents/
        cd /home/vvdn/Tomcat/apache-tomcat-9.0.73/bin
        ./shutdown.sh
        sleep 15
        cp /home/vvdn/Documents/*.war /home/vvdn/Tomcat/apache-tomcat-9.0.73/webapps/
        ./startup.sh
        
    - name: Transfer build file to remote server2
      run: scp -i /root/.ssh/viki_rsa target/*.war ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME_2 }}:/home/vvdn/
    - name: Set up SSH to remote 2
      uses: appleboy/ssh-action@v0.1.10
      with:
          host: ${{ secrets.HOSTNAME_2 }}
          port: ${{secrets.PORT}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_2 }}
          command_timeout: 30m
          script: | 
            mkdir example_folder
            echo "Folder 'example_folder' created successfully."  
            cd /home/vvdn/Documents/apache/apache-tomcat-9.0.73/bin
            ls
            ./shutdown.sh
            sleep 15
            cp /home/vvdn/*.war /home/vvdn/Documents/apache/apache-tomcat-9.0.73/webapps/
            ./startup.sh
