name: Build Maven Project with Java 8
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '8'

    - name: Build with Maven
      run: mvn clean install     

    - name: Transfer build file to remote server1
      run: scp -i /root/.ssh/viki_rsa target/*.war ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }}:/home/vvdn/


    - name: Set up SSH to remote 1
      uses: appleboy/ssh-action@v0.1.10
      with:
          host: ${{ secrets.HOSTNAME }}
          port: ${{secrets.PORT}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          command_timeout: 30m
          script: | 
            cd /home/vvdn/Documents/apache-tomcat-9.0.73/bin
            ls
            ./shutdown.sh
            cp /home/vvdn/*.war /home/vvdn/Documents/apache-tomcat-9.0.73/webapps/
            ./startup.sh
            pwd
            tail -2f ../logs/catalina.out
            
            
            
   

    
            
  

    
        

  
