name: Build Maven Project with Java 8
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '8'

    - name: Build with Maven
      run: mvn clean install     

    - name: Transfer build file to remote server2
      run: scp -i /root/.ssh/viki_rsa target/*.war ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME_2 }}:/home/vvdn/

    - name: Set up SSH to remote 2
      uses: appleboy/ssh-action@v0.1.10
      with:
          host: ${{ secrets.HOSTNAME_2 }}
          port: ${{secrets.PORT}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_2 }}
          command_timeout: 30m
          script: | 
            mkdir example_folder
            echo "Folder 'example_folder' created successfully."  




            
            
            
   

    
            
  

    
        

  
