name: Build Maven Project with Java 8
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '8'

    - name: Build with Maven
      run: mvn clean install
    - name: SonarQube analysis
      run : mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VIKI_PRIVATE}}
        
        
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
          host: ${{ inputs.hostname }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: | 
            echo "Nice Job!!!"
        

  
