name: Build Maven Project with Java 8
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '8'

    - name: Build with Maven
      run: mvn clean install
    - name: SonarQube analysis
      run : mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Deploy to Tomcat
      uses: appleboy/tomcat-deploy@v2
      with:
        host: ${{ secrets.TOMCAT_HOST }}
        port: ${{ secrets.TOMCAT_SSH_PORT }}
        local_file: './target/sample.war'
        remote_file: '/home/vvdn/Tomcat/apache-tomcat-9.0.46/webapps/sample.war'
        username: 'vvdn'

  
