name: Build Maven Project with Java 8
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '8'

    - name: Build with Maven
      run: mvn clean install
    - name: SonarQube analysis
      run : mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VIKI_PRIVATE}}
        
    - name: Copy WAR to Tomcat server
      uses: appleboy/scp-action@v2
      with:
        host: ${{ secrets.TOMCAT_HOST }}
        port: ${{ secrets.TOMCAT_SSH_PORT }}
        key: ${{ secrets.VIKI_PRIVATE }}
        source: './target/sample.war'
        target: 'vvdn@172.20.10.8:/home/vvdn/Tomcat/apache-tomcat-9.0.46/webapps/sample.war'
        

  
